# Generated by Django 4.2.4 on 2023-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='status',
            field=models.CharField(choices=[('opn', 'Open'), ('cls', 'Close')], default='opn', max_length=3),
        ),
    ]
