# Generated by Django 4.2.4 on 2023-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polls_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'ordering': ['-question']},
        ),
        migrations.AddIndex(
            model_name='polls',
            index=models.Index(fields=['-question'], name='polls_polls_questio_b85e83_idx'),
        ),
    ]
